In [1]:
import ROOT
import wafer
import os

In [2]:
test = [0.0 for _ in range(222)]

In [3]:
wafer.fill_wafer_hist(test)

In [5]:
import numpy as np
data = np.loadtxt("../1726589326_all_stdev.txt", delimiter=" ", dtype=float)

print("2D Array from TXT:\n", data)

2D Array from TXT:
 [[0.0926 0.1383 0.1042 ... 0.1107 0.0813 0.1045]
 [0.1131 0.0993 0.0981 ... 0.1225 0.2336 0.13  ]
 [0.0927 0.1118 0.1203 ... 0.0952 0.1146 0.1104]
 [0.1234 0.104  0.086  ... 0.1062 0.1147 0.2848]
 [0.1364 0.1059 0.0903 ... 0.1452 0.0942 0.0935]
 [0.1115 0.1011 0.1001 ... 0.1121 0.0943 0.0947]]


In [6]:
data[0]

array([0.0926, 0.1383, 0.1042, 0.099 , 0.1227, 0.1471, 0.105 , 0.0993,
       0.1076, 0.1151, 0.0949, 0.0824, 0.1208, 0.1288, 0.1724, 0.1408,
       0.0916, 0.0919, 0.1151, 0.0817, 0.1034, 0.1023, 0.199 , 0.1141,
       0.0976, 0.0897, 0.1537, 0.1086, 0.1299, 0.1125, 0.0924, 0.1017,
       0.1316, 0.0909, 0.1554, 0.1197, 0.1389, 0.0941, 0.1326, 0.1948,
       0.0962, 0.1018, 0.0975, 0.1027, 0.1028, 0.1205, 0.1265, 0.0941,
       0.1332, 0.1125, 0.1097, 0.0928, 0.1187, 0.1189, 0.0924, 0.126 ,
       0.1146, 0.1409, 0.119 , 0.1185, 0.12  , 0.1242, 0.1192, 0.1259,
       0.1494, 0.0859, 0.1133, 0.1378, 0.0984, 0.1369, 0.0891, 0.1187,
       0.111 , 0.131 , 0.1028, 0.1022, 0.1126, 0.0953, 0.1095, 0.0925,
       0.0782, 0.1005, 0.1153, 0.0785, 0.0957, 0.1109, 0.1113, 0.0819,
       0.1547, 0.1085, 0.0996, 0.0877, 0.0941, 0.0994, 0.0899, 0.0928,
       0.1436, 0.0861, 0.1293, 0.1062, 0.0713, 0.1265, 0.1534, 0.0782,
       0.1397, 0.0795, 0.0934, 0.0882, 0.104 , 0.0972, 0.1085, 0.1137,
      

In [7]:
wafer.fill_wafer_hist(data[0])

In [10]:
hist = wafer.fill_wafer_hist(data[0])
hist.SetTitle("STDev Map for Module 0")
hist.SetMinimum(0)
hist.SetMaximum(0.5)
canvas = ROOT.TCanvas("m_0", "Hexaplot", 800, 600)
hist.Draw("COLZ TEXT")
output_dir = "."
canvas.SaveAs(
    os.path.join(
        output_dir, "STDev_Map_for_Module_0.png"
    )
)

Warning in <TCanvas::Constructor>: Deleting canvas with same name: m_0
Info in <TCanvas::Print>: png file ./STDev_Map_for_Module_0.png has been created


In [11]:
import argparse
import numpy as np

# Set up argument parser
parser = argparse.ArgumentParser(description="Read a 2D array from a .txt file.")
parser.add_argument("filename", type=str, help="Path to the input text file")
parser.add_argument("--delimiter", type=str, default=" ", help="Delimiter used in the file (default: space)")

args = parser.parse_args()

# Read the TXT file with the specified delimiter
data = np.loadtxt(args.filename, delimiter=args.delimiter).astype(int)

print("2D Array from TXT:\n", data)


usage: ipykernel_launcher.py [-h] [--delimiter DELIMITER] filename
ipykernel_launcher.py: error: unrecognized arguments: -f


SystemExit: 2

/opt/homebrew/Cellar/jupyterlab/4.3.5/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [12]:
script_dir = os.path.dirname(os.path.abspath(__file__))

NameError: name '__file__' is not defined

In [13]:
for i in range (222):
    test[i] = i

hist = wafer.fill_wafer_hist(test)
hist.SetTitle("Num for Module")
hist.SetMinimum(0)
hist.SetMaximum(0.5)
canvas = ROOT.TCanvas("m_0", "Hexaplot", 800, 600)
hist.Draw("COLZ TEXT")
output_dir = "."
canvas.SaveAs(
    os.path.join(
        output_dir, "Map_for_Module.png"
    )
)

Warning in <TCanvas::Constructor>: Deleting canvas with same name: m_0
Info in <TCanvas::Print>: png file ./Map_for_Module.png has been created
